### ISSUE TITLE
about secio

### ISSUE THREAD

**Issue by kingwel-xie** [nervosnetwork/tentacle#242]
I was looking into the rust-libp2p but soon I realized it is quite unlikely to figure out what they are doing, as the code is written like a hell - overwhelming abstraction, stacked state machines...

Later I happend to find this repo, much smaller, and kind of neat.  However, after reading the code, I believe there are something wrong in your secio implementation.

1. secio should be message oriented. In your code, it is not. Messages will be combined as big as the input buffer provided
2. Don't really get why having channels in secio. Code could be very simple if making SecureStream 'AsyncRead/AsyncWrite', in this case we don't have to pass frames with channel. Furthermore the task running SecureStream.next can be eliminated

I'm quite new to rust, but I wonder if the async code in rust has to be written like this: poll in poll with state machine? I tend to believe code should be written in a better way after we have the formal async/await. Otherwise, it is a huge burden for rusters to write and maintain code written like this.

Of course I can make a pull request later if you like, just let me know...

**Comment by driftluo** [comment]
You are right, secio can really only provide the implementation of `AsyncRead/AsyncWrite`, which is also the method I tried in the go implementation:

https://github.com/driftluo/tentacle-go/tree/master/secio

It would be more concise if the first implementation is this way, and the second is to reduce the overhead of the channel, which is a good thing, but I am currently busy solving other problems I found.

If you are interested, welcome to provide PR implementation, but it should be noted that there can be no break in the protocol

**Comment by kingwel-xie** [comment]
Ok, I'll try to cleanup the code then make a pull request. On the other hand, the bug I mentioned has to be fixed, therefore, it can not be fully compatible with the original implemention. I guess it is ok since we are not going to use secio directly as a message based protocol.

BTW, would you like to take a bit more on wechat sometime? I do have some questions about rust async coding. Hopefully you can help anyhow.

**Comment by driftluo** [comment]
> BTW, would you like to take a bit more on wechat sometime? I do have some questions about rust async coding. Hopefully you can help anyhow.

you can find me on wechat，but how can I give you the wechat id？

**Comment by kingwel-xie** [comment]
I can send you mine via your email driftluo@foxmail.com, is that ok?

**Comment by driftluo** [comment]
> I can send you mine via your email [driftluo@foxmail.com](mailto:driftluo@foxmail.com), is that ok?

ok

**Comment by driftluo** [comment]
close by https://github.com/driftluo/tentacle/pull/23
