### ISSUE TITLE
Missing Git Tags for Releases on Crates.io

### ISSUE THREAD

**Issue by eval-exec** [nervosnetwork/tentacle#383]
The Git repository for nervosnetwork/tentacle is missing tags: https://github.com/nervosnetwork/tentacle/tags. 

Meanwhile, the code without tags has already been published to crates.io. We can find the corresponding Git hashes for each version on crates.io (e.g., here: https://docs.rs/crate/tentacle/0.6.4/source/.cargo_vcs_info.json
https://docs.rs/crate/tentacle/0.6.3/source/.cargo_vcs_info.json
https://docs.rs/crate/tentacle/0.6.2/source/.cargo_vcs_info.json 

), and then we can republish the Git tags.

**Comment by quake** [comment]
we should create a workflow to publish, ref: https://github.com/nervosnetwork/ckb-std/blob/master/.github/workflows/release.yml
